language: node_js

# test on node.js versions
node_js:
  - 10
  - 12

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"

