language: node_js

# test on three node.js versions: 0.6 0.8 0.10
node_js:
  - 0.6
  - 0.8
  - 0.10

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"

